projects:
  ecmr:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: 6m2clahxuvg65e5esdv6y6nd3u
      endpoints:
        prod: >-
          https://s5qjr3vjcfd5ndcd3sqkdvrnf4.appsync-api.eu-central-1.amazonaws.com/graphql
